# Etapa de construcción
FROM node:18-alpine AS builder

WORKDIR /frontend

# Copiar package.json y package-lock.json para instalar dependencias primero
COPY frontend/package.json frontend/package-lock.json ./

# Instalar dependencias
RUN npm install --frozen-lockfile

# Copiar el código fuente
COPY frontend ./  

# Construir la aplicación
RUN ls
RUN npm run build
RUN ls


# Etapa de producción (Nginx para servir el contenido estático)
FROM nginx:alpine

# Copiar los archivos generados por Vite a la carpeta de Nginx
COPY --from=builder /frontend/dist /usr/share/nginx/html

# Correct path for nginx.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto por donde servirá Nginx
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
