services:
  api-gateway:
    build: 
      context: ./backend/api-gateway
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - stories-data
      - user-data
    networks:
      - app-network

  stories-data:
    build: 
      context: ./backend/stories-data
      dockerfile: DockerFile
    networks:
      - app-network
  
  user-data:
    build: 
      context: ./backend/user-data
      dockerfile: DockerFile
    networks:
      - app-network

  frontend:
    build: 
      context: ./ #Dejar el path deja que el contenedor pueda acceder al root del proyecto
      dockerfile: ./frontend/DockerFile
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:

# volumes:
#   postgres_data:
