# Use the official Node.js image
FROM node:18-alpine  

# Set the working directory inside the container
WORKDIR /user-data

# Copy package.json and package-lock.json first to leverage caching
COPY package*.json ./  

# Install dependencies
RUN npm install  

# Copy the rest of the project files
COPY . .  

# Build the app (if using TypeScript)
RUN npm run build  

# Command to run the app
CMD ["node", "dist/main.js"]
